version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - internal
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'pguserpass'
      POSTGRES_DB: 'pgDb'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      DB_CONNECTION_STRING: 'Server=postgres;Port=5432;Database=pgDb;User Id=pguser;Password=pguserpass'
      CACHE_CONNECTION_STRING: 'redis:6379'
      TOKEN_HTTPS_META: 'true'
      TOKEN_AUDIENCE: 'https://sandiegomelloroos.com'
      TOKEN_ISSUER: 'https://api.sandiegomelloroos.com'
    networks:
      - internal
      - web
  nuxt1:
    container_name: nuxt1
    build:
      context: ./nuxt-client
      dockerfile: Dockerfile
    restart: always
    expose:
      - 3000
    environment:
      API_URL: 'https://api.sandiegomelloroos.com'
      APP_ENV: 'PROD'
      CLIENT_ID: '1'
      CLIENT_URL: 'https://sandiegomelloroos.com'
      SITE_TITLE: 'San Diego Mello Roos Tax Lookup'
    command: 'yarn start'
    depends_on:
      - api
    networks:
      - web

volumes:
  postgres_data:
  redis_data:

networks:
  internal:
  web:
    external:
      name: nginx_web
