version: '3'

services:
  proxy:
    container_name: proxy
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staging:/etc/nginx/conf.d
      - ./staging/certbot/conf:/etc/letsencrypt
      - ./staging/certbot/www:/var/www/certbot
    networks:
      - web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    volumes:
      - ./staging/certbot/conf:/etc/letsencrypt
      - ./staging/certbot/www:/var/www/certbot
    networks:
      - web
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  web:
    external:
      name: nginx_web
